### ISSUE TITLE
when i run app ,it says Traceback (most recent call last),errors:File "E:\AS2021\chaquopy-matplotlib-master\app\build\generated\python\bp.zip\pip\_vendor\urllib3\response.py", line 397, in _error_catcher     yield   File "E:\AS2021\chaquopy-matplotlib-master\app\build\generated\python\bp.zip\pip\_vendor\urllib3\response.py", line 479, in read     data = self._fp.read(amt)   File "E:\AS2021\chaquopy-matplotlib-master\app\build\generated\python\bp.zip\pip\_vendor\cachecontrol\filewrapper.py", line 62, in read     data = self.__fp.read(amt)

### ISSUE THREAD

**Issue by newer-android** [chaquo/chaquopy-matplotlib#2]

**Comment by mhsmith** [comment]
Please post the complete build log in a comment.

**Comment by mhsmith** [comment]
If this is still a problem, please post the requested information, and I'll reopen the issue.
